@echo off
echo Creating database if not exists...
c:\xampp\mysql\bin\mysql.exe -u root --default-character-set=utf8mb4 -e "CREATE DATABASE IF NOT EXISTS quiztests CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"

echo Creating Tables...
c:\xampp\mysql\bin\mysql.exe -u root --default-character-set=utf8mb4 -D quiztests < database_setup.sql
c:\xampp\mysql\bin\mysql.exe -u root --default-character-set=utf8mb4 -D quiztests < sql\create_user_stats.sql

echo Cleaning old data...
c:\xampp\mysql\bin\mysql.exe -u root --default-character-set=utf8mb4 -D quiztests < sql\clean_all.sql

echo Running Setup...
c:\xampp\mysql\bin\mysql.exe -u root --default-character-set=utf8mb4 -D quiztests < sql\seed_setup_french.sql

echo Seeding Badges...
c:\xampp\mysql\bin\mysql.exe -u root --default-character-set=utf8mb4 -D quiztests < sql\seed_badges_french.sql

echo Seeding Java...
c:\xampp\mysql\bin\mysql.exe -u root --default-character-set=utf8mb4 -D quiztests < sql\seed_java_french.sql

echo Seeding Python...
c:\xampp\mysql\bin\mysql.exe -u root --default-character-set=utf8mb4 -D quiztests < sql\seed_python_french.sql

echo Seeding JS...
c:\xampp\mysql\bin\mysql.exe -u root --default-character-set=utf8mb4 -D quiztests < sql\seed_js_french.sql

echo Seeding SQL...
c:\xampp\mysql\bin\mysql.exe -u root --default-character-set=utf8mb4 -D quiztests < sql\seed_sql_french.sql

echo Seeding C++...
c:\xampp\mysql\bin\mysql.exe -u root --default-character-set=utf8mb4 -D quiztests < sql\seed_cpp_french.sql

echo Seeding C...
c:\xampp\mysql\bin\mysql.exe -u root --default-character-set=utf8mb4 -D quiztests < sql\seed_c_french.sql

echo Seeding HTML...
c:\xampp\mysql\bin\mysql.exe -u root --default-character-set=utf8mb4 -D quiztests < sql\seed_html_french.sql

echo Seeding CSS...
c:\xampp\mysql\bin\mysql.exe -u root --default-character-set=utf8mb4 -D quiztests < sql\seed_css_french.sql

echo Seeding Kotlin...
c:\xampp\mysql\bin\mysql.exe -u root --default-character-set=utf8mb4 -D quiztests < sql\seed_kotlin_french.sql

echo Seeding PHP...
c:\xampp\mysql\bin\mysql.exe -u root --default-character-set=utf8mb4 -D quiztests < sql\seed_php_french.sql

echo Done!
